### ISSUE TITLE
Demo page

### ISSUE THREAD

**Issue by ivmarcos** [mikayel/React-Composite-View#1]
As a suggestion, create a demo page.

**Comment by mikayel** [comment]
Thanks for suggestion, I will create as soon as I can.

It will be similar to this http://mikayel.com/react-cv-demo/
I have made this demo for the same Composite View Paten and React old
version  https://github.com/mikayel/react-cv

regards,
Mikayel

**Comment by ivmarcos** [comment]
Tks! @mikayel

**Comment by mikayel** [comment]
I have created the demo page https://webinos.com/React-Composite-View-Demo/
